from viper import functions as utils

module control:
    snakefile: "rules/control.smk"

# config.setdefault("nfiles", "1")
# config.setdefault("ProcessingStyle", "bulk")
use rule * from control
use rule jgf from control with:
    params:
        nfiles=config['nfiles']


# This is the user-defined workflow and the main point-of-entry for users.
# Needs to be provided
middle_layer=config["UserWorkflow"]
include: middle_layer

def check_jgf(wildcards):
    with checkpoints.jgf.get().output[0].open() as f:
        nlines = sum(1 for line in f)
    if nlines == 0:
        return []
    else:
        output = []
        for tar in final_stages:
            for out in tar.output:
                output += expand(out, i=[i for i in range(nlines)])
            print(output)
        return output + ['justin-processed-dids.txt']

rule all:
    input:
        check_jgf
        # utils.make_check_jgf(
        #     checkpoints,
        #     final_stages,
        #     expand,
        # )
