from viper import functions as utils

module control:
    snakefile: "rules/control.smk"

# config.setdefault("nfiles", "1")
# config.setdefault("ProcessingStyle", "bulk")
use rule * from control
use rule jgf from control with:
    params:
        nfiles=config['nfiles']


# This is the user-defined workflow and the main point-of-entry for users.
# Needs to be provided
middle_layer=config["UserWorkflow"]
include: middle_layer

processing_style=config["ProcessingStyle"]

rule all:
    input:
        utils.make_check_jgf(
            checkpoints,
            final_stages,
            expand,
            processing_style=processing_style
        )
